// Copyright (C) 2021, Stegvision, Inc.

export default {
  back: require('../components/assets/back.png'),
  camera: require('../components/assets/camera.png'),
  right: require('../components/assets/right.png'),
  help: require('../components/assets/help.png'),
  scan: require('../components/assets/scan.png'),
  detail: require('../components/assets/detail.png'),
  right_arrow: require('../components/assets/right_arrow.png'),
  unknown: require('../components/assets/unknown.png'),
  camera_scan: require('../components/assets/camera_scan.png'),
  scan_button: require('../components/assets/scan_button.png'),
  name_icon: require('../components/assets/name_icon.png'),
  jab: require('../components/assets/jab.png'),
  round_icon: require('../components/assets/round_icon.png'),
  scan_another: require('../components/assets/scan_another.png'),
  fail: require('../components/assets/fail.png'),
  menu: require('../components/assets/menu.png'),
  question: require('../components/assets/question.png'),
  close: require('../components/assets/close.png'),
  line: require('../components/assets/line.png'),
  ecotton_thumbnail: require('../components/assets/ecotton_thumbnail.png'),
  
  backArrow: require('../components/assets/backArrow.png'),
  backgroundImg: require('../components/assets/backgroundImg.png'),
  plus: require('../components/assets/plus.png'),
  danger: require('../components/assets/danger.png'),
  appLogo: require('../components/assets/appLogo.png'),
  tick: require('../components/assets/tick.png'),
  leftArrow: require('../components/assets/leftArrow.png'),
  rightArrow: require('../components/assets/rightArrow.png'),
  c1: require('../components/assets/c1.png'),
  c2: require('../components/assets/c2.png'),
  c3: require('../components/assets/c3.png'),
  count1: require('../components/assets/count1.png'),
  count2: require('../components/assets/count2.png'),
  count3: require('../components/assets/count3.png'),
};
